server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/NovaCapital?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=NovaCapitalSecretKey2024SuperSeguraParaJWT!!
app.jwt.expiration=86400000

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Europe/Madrid